name: Laravel CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.1
        env:
          MYSQL_ROOT_PASSWORD:
          MYSQL_DATABASE: ktwing_live
          MYSQL_USER: root
          MYSQL_PASSWORD:
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: mbstring, bcmath, mysql, dom, curl
        ini-values: post_max_size=256M, upload_max_filesize=256M
        coverage: xdebug

    - name: Install dependencies
      run: |
        composer install
        cp .env.example .env
        php artisan key:generate
        php artisan config:cache
        php artisan migrate --seed

    - name: Run tests
      run: vendor/bin/phpunit
